---

- name: Create Required Redis Build Directories
  file:
    path: "{{ redis_sources_dir }}"
    state: directory

- name: Create Data Home
  file:
    path: "{{ redis_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Required Redis Home Directories
  file:
    path: "{{ redis_home_dir }}"
    state: directory


- name: Download and verify Redis
  get_url:
    url: "{{ redis_download_url }}"
    dest: "{{ redis_sources_dir }}/redis-{{redis_version}}.tar.gz"
    checksum: "sha256:{{redis_checksum}}"

- name: Unzip Redis
  unarchive:
    src: "{{ redis_sources_dir }}/redis-{{redis_version}}.tar.gz"
    dest: "{{ redis_sources_dir }}"
    remote_src: yes
    creates: /usr/src/redis/Makefile


#- name: Copy the Redis conf file
#  copy:
#    src: "{{ redis_sources_dir }}/redis-{{redis_version}}/redis.conf"
#    dest: /etc/redis/
#    owner: "{{redis_user}}"
#    group: "{{redis_group}}"
#    remote_src: yes
#    mode: 0644

- name: Compile Redis sources
  make:
    chdir: "{{ redis_sources_dir }}/redis-{{redis_version}}/"
    target: install

#- name: Copy the redis-senitel file
#  copy:
#    src: "{{ redis_sources_dir }}/redis-{{redis_version}}/src/redis-sentinel"
#    dest: /usr/local/bin/
#    owner: "{{redis_user}}"
#    group: "{{redis_group}}"
#    remote_src: yes
#    mode: 0755